files:
  ignore:
    - 'src/scss/_normalize.scss'
rules:
  property-sort-order:
    - order: 'smacss'
  mixins-before-declarations:
    - exclude: ['break']
  class-name-format:
    - convention: 'hyphenatedbem'
  no-qualifying-elements:
    allow-element-with-attribute: true
  force-attribute-nesting: 0
  no-url-protocols: 0
  no-url-domains: 0
